# Generated by Django 4.0.4 on 2022-05-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_A_Chair_App', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
